// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw88kPbly4_w3I6hZpo3cIcsxdpfwOWek',
    appId: '1:851911209590:web:bca2a7b7f7f297d1916557',
    messagingSenderId: '851911209590',
    projectId: 'chat-app-ed2b4',
    authDomain: 'chat-app-ed2b4.firebaseapp.com',
    storageBucket: 'chat-app-ed2b4.appspot.com',
    measurementId: 'G-3PM7F546BE',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo1UyT7TFzrEMD2XkN3-Y09OV5uVKYOTE',
    appId: '1:851911209590:ios:7bbc9498fd811142916557',
    messagingSenderId: '851911209590',
    projectId: 'chat-app-ed2b4',
    storageBucket: 'chat-app-ed2b4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo1UyT7TFzrEMD2XkN3-Y09OV5uVKYOTE',
    appId: '1:851911209590:ios:7bbc9498fd811142916557',
    messagingSenderId: '851911209590',
    projectId: 'chat-app-ed2b4',
    storageBucket: 'chat-app-ed2b4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw88kPbly4_w3I6hZpo3cIcsxdpfwOWek',
    appId: '1:851911209590:web:f9e5b8bdfc6673fc916557',
    messagingSenderId: '851911209590',
    projectId: 'chat-app-ed2b4',
    authDomain: 'chat-app-ed2b4.firebaseapp.com',
    storageBucket: 'chat-app-ed2b4.appspot.com',
    measurementId: 'G-SGTCJBKG1J',
  );
}
